name: Release Preparation Minimize JS Versions

on:
  pull_request:
    types: [labeled]

jobs:
  run-script-and-commit-changes:
    if: github.event.label.name == 'Pending Deploy'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      run: python ./includes/build_scripts/build_js_version_tick.py
    - name: Commit changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add includes/js/*
        git commit -m "GHA_BUILD: Minimize JS Versions"
        git push origin ${{ github.event.pull_request.head.ref }}