name: release-te-custom-mods
run-name: Build ${{ github.ref_name }}
on:
  pull_request:
    branches-ignore:
      #the release branch will is a permanent branch and has the build. A separate PR
      #is created for you to approve that the build is ok
      - 'release/**'
jobs:
  build_release_pr:
    runs-on: windows-latest
    if: contains(git ls-remote --heads origin release-, 'release-')
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: create release branch
        run: git checkout -b release-${{github.GITHUB_REF}} ${{github.GITHUB_SHA}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: push release branch
        run: git push --set-upstream origin release-${{github.GITHUB_REF}} ${{github.GITHUB_SHA}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: create pull request
        run: gh pr create -B master -H test-branch-that-exists --title "Created by GH Actions!" --body "The first step in my attempt to automatically build and release plugin updates, which can then be downloaded and installed in Wordpress."
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}