name: Release Preparation

on:
  pull_request:
    types: [labeled]

jobs:
  prepare-for-release-build:
    if: github.event.label.name == 'Deploy Pending'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Run JS Version Minimization Script
      run: |
        python ./includes/build_scripts/build_js_version_minimize.py > ./includes/build_scripts/build_log.txt
    - name: Commit Changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "GHA_BUILD: Minimize JS Versions"
        git push origin ${{ github.event.pull_request.head.ref }}
    - name: Run CSS Version Minimization Script
      run: |
        python ./includes/build_scripts/build_css_version_minimize.py >> ./includes/build_scripts/build_log.txt
    - name: Commit Changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "GHA_BUILD: Minimize CSS Versions"
        git push origin ${{ github.event.pull_request.head.ref }}
    - name: Run Plugin Version Incrementer
      run: |
        python ./includes/build_scripts/build_update_plugin_version.py
    - name: Commit Changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        PLUGIN_VERSION=$(grep -oP "(?<=te-custom-mods: )[0-9]+\.[0-9]+\.[0-9]+" ./prod-versions.ini)
        git commit -m "GHA_BUILD: Increment Plugin Version to $PLUGIN_VERSION"
        git push origin ${{ github.event.pull_request.head.ref }}
    - name: Zip Plugin
      run: |
        python ./includes/build_scripts/build_zip_plugin.py >> ./includes/build_scripts/build_log.txt
    - name: Commit Changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "GHA_BUILD: Zip Plugin"
        git push origin ${{ github.event.pull_request.head.ref }}
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        RELEASE_BRANCH=${{ github.event.pull_request.head.ref }}
        RELEASE_BODY="""${{ github.event.pull_request.body }}
        
        ${{ github.event.pull_request.html_url }}"""
        RELEASE_TAG=$(grep -oP "(?<=te-custom-mods: )[0-9]+\.[0-9]+\.[0-9]+" ./prod-versions.ini)
        RELEASE_TITLE="$RELEASE_TAG: ${{ github.event.pull_request.title }}"
        gh release create "TEST$RELEASE_TAG" --title "$RELEASE_TITLE" --notes "$RELEASE_BODY" --target $RELEASE_BRANCH -d
        gh release upload "TEST$RELEASE_TAG" ./te-custom-mods.zip