name: RSS Update

on:
  schedule:
    - cron: '30 23 * * *'
  pull_request:
    types: [labeled]

jobs:
  rss-update:
    if: github.event.label.name == 'Update RSS'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Update RSS Feed
      run: |
        python ./RSS/update_rss.py > ./RSS/rss_output.txt
    - name: Commit Changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "GHA_RSS: Update RSS Feeds"
        git push origin DEV-custom-rss