name: RSS Update

on:
  schedule:
  - cron: '7 0 * * *'
  - cron: '7 1 * * *'
  - cron: '7 2 * * *'
  - cron: '7 3 * * *'
  - cron: '7 4 * * *'
  - cron: '7 5 * * *'
  - cron: '7 6 * * *'
  - cron: '37 6 * * *'
  - cron: '7 7 * * *'
  - cron: '27 7 * * *'
  - cron: '37 7 * * *'
  - cron: '47 7 * * *'
  - cron: '57 7 * * *'
  - cron: '7 8 * * *'
  - cron: '17 8 * * *'
  - cron: '27 8 * * *'
  - cron: '37 8 * * *'
  - cron: '47 8 * * *'
  - cron: '57 8 * * *'
  - cron: '7 9 * * *'
  - cron: '17 9 * * *'
  - cron: '27 9 * * *'
  - cron: '37 9 * * *'
  - cron: '7 10 * * *'
  - cron: '37 10 * * *'
  - cron: '7 11 * * *'
  - cron: '37 11 * * *'
  - cron: '7 12 * * *'
  - cron: '37 12 * * *'
  - cron: '7 13 * * *'
  - cron: '37 13 * * *'
  - cron: '7 14 * * *'
  - cron: '37 14 * * *'
  - cron: '7 15 * * *'
  - cron: '37 15 * * *'
  - cron: '7 16 * * *'
  - cron: '37 16 * * *'
  - cron: '7 17 * * *'
  - cron: '7 18 * * *'
  - cron: '7 19 * * *'
  - cron: '7 20 * * *'
  - cron: '7 21 * * *'
  - cron: '7 22 * * *'
  - cron: '7 23 * * *'

jobs:
  rss-update:
    continue-on-error: true
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with: { ref: DEV-custom-rss }
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests
    - name: Update RSS Feed
      run: |
        python ./RSS/update_rss.py > ./RSS/rss_output.txt
    - name: Commit Changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "GHA_RSS: Update RSS Feeds"
        git push origin DEV-custom-rss
