name: RSS Update

on:
  pull_request:
    types: [labeled]

jobs:
  rss-update:
    continue-on-error: true
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with: { ref: rss-machine-broke }
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests
        pip install requests-html
    - name: Update RSS Feed
      run: |
        python ./RSS/update_rss.py > ./RSS/rss_output.txt
    - name: Commit Changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "GHA_RSS: Update RSS Feeds"
        git push origin rss-machine-broke
