name: RSS Update

on:
  schedule:
    - cron: '30 23 * * *'
  pull_request:
    types: [labeled]

jobs:
  rss-update:
    if: github.event.label.name == 'Deploy Pending'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Run JS Version Minimization Script
      run: |
        curl https://tanks-encyclopedia.com/ -s | tac | grep -oP '(?<=\s\s\s\s\s<a href=")https://tanks-encyclopedia.com/[a-zA-Z\s/\.\d\-]+.>.+(?=<)' | tail -1 | python ./RSS/update_rss.py
    - name: Commit Changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "GHA_RSS: Update RSS Feeds"
        git push origin DEV-custom-rss